In [4]:
import pandas as pd

# BASIC

data=['ABC','DEF','GHI']
ds=pd.Series(data)
print(ds)
print(type(ds))

# INDEX

ds1=pd.Series(data,index=['A','B','C'])
print(ds1)

# INDEX WITH VALUES

d={'A':20,'B':30,'C':40}
ds2=pd.Series(d)
print(ds2)

# RANGE

ds3=pd.Series(range(51,61))
print(ds3)

0    ABC
1    DEF
2    GHI
dtype: object
<class 'pandas.core.series.Series'>
A    ABC
B    DEF
C    GHI
dtype: object
A    20
B    30
C    40
dtype: int64
0    51
1    52
2    53
3    54
4    55
5    56
6    57
7    58
8    59
9    60
dtype: int64

# DataFrame()

In [10]:
import pandas as pd

data={'name':['Roy','Harsh','Om','Veer'],
      'div':['D1','D2','D3','D4'],
       'marks':[30,40,28,26]}
df=pd.DataFrame(data)
print(df)
print(type(df))

# list in list

d=[['A',20,'D1'],
   ['A',20,'D1'],
   ['A',20,'D1']]
df1=pd.DataFrame(d,columns=['name','marks','div'],index=['AA','BB','CC'])
print(df1)

# LIST OF DICT

s1=pd.Series([20,21,22])
s2=pd.Series([23,24,25])
s3=pd.Series([26,27,28])
df2=pd.DataFrame({'col 1':s1,'col 2':s2})
print(df2)

# DICT in LIST

d1=[{'A':20,'B':30},
    {'A':21,'B':40},
    {'A':22,'B':50}]
df3=pd.DataFrame(d1)
print(df3)

    name div  marks
0    Roy  D1     30
1  Harsh  D2     40
2     Om  D3     28
3   Veer  D4     26
<class 'pandas.core.frame.DataFrame'>
   name  marks div
AA    A     20  D1
BB    A     20  D1
CC    A     20  D1
   col 1  col 2
0     20     23
1     21     24
2     22     25
    A   B
0  20  30
1  21  40
2  22  50

In [19]:
# AUTO.MPG CODE FOR CSV TO DATAFRAME

import pandas as pd
df=pd.read_csv('auto-mpg.csv')
print(df)

# DATAFRAME TO CSV

df.to_csv('mycsv.csv')

# Set_Index

# df.set_index('car name',drop=True)

df.set_index('car name',drop=True,inplace=True)
print(df)

df.reset_index()

df.reset_index(inplace=True)
print(df)

      mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0
1    15.0          8         350.0        165    3693          11.5
2    18.0          8         318.0        150    3436          11.0
3    16.0          8         304.0        150    3433          12.0
4    17.0          8         302.0        140    3449          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4         140.0         86    2790          15.6
394  44.0          4          97.0         52    2130          24.6
395  32.0          4         135.0         84    2295          11.6
396  28.0          4         120.0         79    2625          18.6
397  31.0          4         119.0         82    2720          19.4

     model year  origin                   car name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]
                            mpg  cylinders  displacement horsepower  weight  \
car name
chevrolet chevelle malibu  18.0          8         307.0        130    3504
buick skylark 320          15.0          8         350.0        165    3693
plymouth satellite         18.0          8         318.0        150    3436
amc rebel sst              16.0          8         304.0        150    3433
ford torino                17.0          8         302.0        140    3449
...                         ...        ...           ...        ...     ...
ford mustang gl            27.0          4         140.0         86    2790
vw pickup                  44.0          4          97.0         52    2130
dodge rampage              32.0          4         135.0         84    2295
ford ranger                28.0          4         120.0         79    2625
chevy s-10                 31.0          4         119.0         82    2720

                           acceleration  model year  origin
car name
chevrolet chevelle malibu          12.0          70       1
buick skylark 320                  11.5          70       1
plymouth satellite                 11.0          70       1
amc rebel sst                      12.0          70       1
ford torino                        10.5          70       1
...                                 ...         ...     ...
ford mustang gl                    15.6          82       1
vw pickup                          24.6          82       2
dodge rampage                      11.6          82       1
ford ranger                        18.6          82       1
chevy s-10                         19.4          82       1

[398 rows x 8 columns]
                      car name   mpg  cylinders  displacement horsepower  \
0    chevrolet chevelle malibu  18.0          8         307.0        130
1            buick skylark 320  15.0          8         350.0        165
2           plymouth satellite  18.0          8         318.0        150
3                amc rebel sst  16.0          8         304.0        150
4                  ford torino  17.0          8         302.0        140
..                         ...   ...        ...           ...        ...
393            ford mustang gl  27.0          4         140.0         86
394                  vw pickup  44.0          4          97.0         52
395              dodge rampage  32.0          4         135.0         84
396                ford ranger  28.0          4         120.0         79
397                 chevy s-10  31.0          4         119.0         82

     weight  acceleration  model year  origin
0      3504          12.0          70       1
1      3693          11.5          70       1
2      3436          11.0          70       1
3      3433          12.0          70       1
4      3449          10.5          70       1
..      ...           ...         ...     ...
393    2790          15.6          82       1
394    2130          24.6          82       2
395    2295          11.6          82       1
396    2625          18.6          82       1
397    2720          19.4          82       1

[398 rows x 9 columns]

# Attributes of DataFrames

In [32]:
import pandas as pd
df=pd.read_csv('auto-mpg.csv')
print(df)
df.head()

      mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0
1    15.0          8         350.0        165    3693          11.5
2    18.0          8         318.0        150    3436          11.0
3    16.0          8         304.0        150    3433          12.0
4    17.0          8         302.0        140    3449          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4         140.0         86    2790          15.6
394  44.0          4          97.0         52    2130          24.6
395  32.0          4         135.0         84    2295          11.6
396  28.0          4         120.0         79    2625          18.6
397  31.0          4         119.0         82    2720          19.4

     model year  origin                   car name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [21]:
df.head(7)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala

In [22]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [23]:
df.tail(9)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
389,22.0,6,232.0,112,2835,14.7,82,1,ford granada l
390,32.0,4,144.0,96,2665,13.9,82,3,toyota celica gt
391,36.0,4,135.0,84,2370,13.0,82,1,dodge charger 2.2
392,27.0,4,151.0,90,2950,17.3,82,1,chevrolet camaro
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [24]:
df.shape

(398, 9)

In [25]:
df.size

3582

In [26]:
df.ndim

2

In [27]:
df.values

array([[18.0, 8, 307.0, ..., 70, 1, 'chevrolet chevelle malibu'],
       [15.0, 8, 350.0, ..., 70, 1, 'buick skylark 320'],
       [18.0, 8, 318.0, ..., 70, 1, 'plymouth satellite'],
       ...,
       [32.0, 4, 135.0, ..., 82, 1, 'dodge rampage'],
       [28.0, 4, 120.0, ..., 82, 1, 'ford ranger'],
       [31.0, 4, 119.0, ..., 82, 1, 'chevy s-10']], dtype=object)

In [28]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [29]:
df.index

RangeIndex(start=0, stop=398, step=1)

In [30]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [31]:
df.sample(2)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
88,14.0,8,302.0,137,4042,14.5,73,1,ford gran torino
63,14.0,8,400.0,175,4385,12.0,72,1,pontiac catalina

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [35]:
df.describe()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [36]:
df.describe(include='all')

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
count,398.000000,398.000000,398.000000,398,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,94,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,150,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,22,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,NaN,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,NaN,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,NaN,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,NaN,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,NaN,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,NaN,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,NaN,5140.000000,24.800000,82.000000,3.000000,NaN

In [40]:
df.describe(exclude='float64')

         cylinders horsepower       weight  model year      origin    car name
count   398.000000        398   398.000000  398.000000  398.000000         398
unique         NaN         94          NaN         NaN         NaN         305
top            NaN        150          NaN         NaN         NaN  ford pinto
freq           NaN         22          NaN         NaN         NaN           6
mean      5.454774        NaN  2970.424623   76.010050    1.572864         NaN
std       1.701004        NaN   846.841774    3.697627    0.802055         NaN
min       3.000000        NaN  1613.000000   70.000000    1.000000         NaN
25%       4.000000        NaN  2223.750000   73.000000    1.000000         NaN
50%       4.000000        NaN  2803.500000   76.000000    1.000000         NaN
75%       8.000000        NaN  3608.000000   79.000000    2.000000         NaN
max       8.000000        NaN  5140.000000   82.000000    3.000000         NaN

In [46]:
df.describe(percentiles=[0.36,0.85])

,mpg,cylinders,displacement,weight,acceleration,model year,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
36%,19.092000,4.000000,120.000000,2471.360000,14.500000,74.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
85%,32.245000,8.000000,318.000000,4067.650000,18.500000,80.450000,3.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [47]:
df.loc[1]

mpg                            15
cylinders                       8
displacement                  350
horsepower                    165
weight                       3693
acceleration                 11.5
model year                     70
origin                          1
car name        buick skylark 320
Name: 1, dtype: object

In [48]:
df.iloc[1]

mpg                            15
cylinders                       8
displacement                  350
horsepower                    165
weight                       3693
acceleration                 11.5
model year                     70
origin                          1
car name        buick skylark 320
Name: 1, dtype: object

In [49]:
df.loc[0:5]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500

In [50]:
df.iloc[0:5]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [51]:
df.loc[0:5,'horsepower']

0    130
1    165
2    150
3    150
4    140
5    198
Name: horsepower, dtype: object

In [52]:
# INVALID Syntax
df.iloc[0:5,'horsepower']

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [62]:
df.iloc[1:5,2]

1    350.0
2    318.0
3    304.0
4    302.0
Name: displacement, dtype: float64

In [60]:
df.loc[1:5,2]

KeyError: 2

In [59]:
df.iloc[1:5,2]

1    350.0
2    318.0
3    304.0
4    302.0
Name: displacement, dtype: float64

In [58]:
df.loc[:,'horsepower']

0      130
1      165
2      150
3      150
4      140
      ...
393     86
394     52
395     84
396     79
397     82
Name: horsepower, Length: 398, dtype: object

In [2]:
import pandas as pd
data={'name':['kohli','Rohit','rahul','gill'],
      'runs':[12000,10000,6000,4000],
       'avg':[69.5,46.7,51.2,49.3]}
df=pd.DataFrame(data)
df.loc[1,'name']

'Rohit'

In [6]:
import pandas as pd
data={'name':['kohli','Rohit','rahul','gill'],
      'runs':[12000,10000,6000,4000],
       'avg':[69.5,46.7,51.2,49.3]}
df=pd.DataFrame(data)
df.loc[4]=['pant',5000,49.5]
print(df)

    name   runs   avg
0  kohli  12000  69.5
1  Rohit  10000  46.7
2  rahul   6000  51.2
3   gill   4000  49.3
4   pant   5000  49.5

In [11]:
import pandas as pd
data={'name':['kohli','Rohit','rahul','gill'],
      'runs':[12000,10000,6000,4000],
       'avg':[69.5,46.7,51.2,49.3]}
df=pd.DataFrame(data)
df.loc[4]=['pant',5000,49.5]
print(df)

print("-----------------------------------")

df.loc[:,'Strike_Rate']=[200,160,120,80,50]
print(df)

print("-----------------------------------")

df['performance']='good'
df.loc[df['avg']<50,'performance']='Average'
print(df)

    name   runs   avg
0  kohli  12000  69.5
1  Rohit  10000  46.7
2  rahul   6000  51.2
3   gill   4000  49.3
4   pant   5000  49.5
-----------------------------------
    name   runs   avg  Strike_Rate
0  kohli  12000  69.5          200
1  Rohit  10000  46.7          160
2  rahul   6000  51.2          120
3   gill   4000  49.3           80
4   pant   5000  49.5           50
-----------------------------------
    name   runs   avg  Strike_Rate performance
0  kohli  12000  69.5          200        good
1  Rohit  10000  46.7          160     Average
2  rahul   6000  51.2          120        good
3   gill   4000  49.3           80     Average
4   pant   5000  49.5           50     Average

In [22]:
import pandas as pd
data={'name':['kohli','Rohit','rahul','gill','Rohit','kohli'],
      'runs':[12000,10000,6000,4000,12000,10000],
       'avg':[69.5,46.7,51.2,49.3,69.5,46.7]}
df=pd.DataFrame(data)
print(df)

print("-----------------------------------")

df['name'].unique()

    name   runs   avg
0  kohli  12000  69.5
1  Rohit  10000  46.7
2  rahul   6000  51.2
3   gill   4000  49.3
4  Rohit  12000  69.5
5  kohli  10000  46.7
-----------------------------------

array(['kohli', 'Rohit', 'rahul', 'gill'], dtype=object)

In [20]:
df['name'].nunique()

4

In [21]:
df['name'].value_counts(ascending=True)

gill     1
rahul    1
kohli    2
Rohit    2
Name: name, dtype: int64

In [23]:
df['name'].value_counts()

Rohit    2
kohli    2
rahul    1
gill     1
Name: name, dtype: int64

# sales data

In [6]:
import pandas as pd

df=pd.read_csv('sales_data.csv')
print(df)

df.isna()

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
7       NaN    NaN      NaN       NaN
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

     name  region  sales  expenses
0   False    True  False     False
1   False   False  False     False
2   False   False   True      True
3   False    True   True      True
4   False   False  False     False
5   False   False  False     False
6   False   False  False     False
7    True    True   True      True
8   False   False  False     False
9   False   False  False     False
10  False   False  False     False

In [9]:
df.isna().sum()

name        1
region      3
sales       3
expenses    3
dtype: int64

In [10]:
df.dropna()

      name region    sales  expenses
1     Emma  North  52000.0   43000.0
4   Edward   West  42000.0   38000.0
5   Thomas   West  72000.0   39000.0
6    Ethan  South  49000.0   42000.0
8     Arun   West  67000.0   39000.0
9    Anika   East  65000.0   50000.0
10   Paulo  South  67000.0   45000.0

In [11]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [12]:
df.dropna(subset=['sales'])

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [8]:
import pandas as pd

df=pd.read_csv('sales_data.csv')
print(df)
df.dropna(thresh=2)

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
3    Markus    NaN      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
7       NaN    NaN      NaN       NaN
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [9]:
df.fillna(0)

       name region    sales  expenses
0   William      0  50000.0   42000.0
1      Emma  North  52000.0   43000.0
2     Sofia   East      0.0       0.0
3    Markus      0      0.0       0.0
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
7         0      0      0.0       0.0
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

In [10]:
df['sales'].fillna(df['sales'].mean())

0     50000.0
1     52000.0
2     58000.0
3     58000.0
4     42000.0
5     72000.0
6     49000.0
7     58000.0
8     67000.0
9     65000.0
10    67000.0
Name: sales, dtype: float64

In [11]:
df.drop('sales',axis=1)

       name region  expenses
0   William    NaN   42000.0
1      Emma  North   43000.0
2     Sofia   East       NaN
3    Markus    NaN       NaN
4    Edward   West   38000.0
5    Thomas   West   39000.0
6     Ethan  South   42000.0
7       NaN    NaN       NaN
8      Arun   West   39000.0
9     Anika   East   50000.0
10    Paulo  South   45000.0

In [14]:
df.drop(columns=['sales','expenses','name'])

   region
0     NaN
1   North
2    East
3     NaN
4    West
5    West
6   South
7     NaN
8    West
9    East
10  South

In [13]:
df.drop(index=[1,3])

       name region    sales  expenses
0   William    NaN  50000.0   42000.0
2     Sofia   East      NaN       NaN
4    Edward   West  42000.0   38000.0
5    Thomas   West  72000.0   39000.0
6     Ethan  South  49000.0   42000.0
7       NaN    NaN      NaN       NaN
8      Arun   West  67000.0   39000.0
9     Anika   East  65000.0   50000.0
10    Paulo  South  67000.0   45000.0

# Data Cleaning

In [17]:
import pandas as pd
data=({'name':['A','B','A','C'],'marks':[85,77,85,90]})
df=pd.DataFrame(data)
print(df)

df.duplicated()

  name  marks
0    A     85
1    B     77
2    A     85
3    C     90

0    False
1    False
2     True
3    False
dtype: bool

In [18]:
df.drop_duplicates()

  name  marks
0    A     85
1    B     77
3    C     90

In [22]:
df.drop_duplicates(keep='last')

  name  marks
1    B     77
2    A     85
3    C     90

In [23]:
df.drop_duplicates(keep='first')

  name  marks
0    A     85
1    B     77
3    C     90

# Sort

In [30]:
df.sort_values(by='marks')

  name  marks
1    B     77
0    A     85
2    A     85
3    C     90

In [26]:
df.sort_values(by='marks',ascending=False)

  name  marks
3    C     90
0    A     85
2    A     85
1    B     77

In [27]:
df.sort_index(ascending=False)

  name  marks
3    C     90
2    A     85
1    B     77
0    A     85

In [29]:
df.sort_index(axis=1)

   marks name
0     85    A
1     77    B
2     85    A
3     90    C

In [31]:
df[df['marks']>80]

  name  marks
0    A     85
2    A     85
3    C     90

In [34]:
df[(df['marks']>80) & (df['marks']<90)]

  name  marks
0    A     85
2    A     85

In [37]:
df[(df['marks']>80) | (df['marks']<90)]

  name  marks
0    A     85
1    B     77
2    A     85
3    C     90

In [39]:
df=pd.read_csv('auto-mpg.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64
 7   origin        398 non-null    int64
 8   car name      398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [40]:
df['horsepower'].unique()

array(['130', '165', '150', '140', '198', '220', '215', '225', '190',
       '170', '160', '95', '97', '85', '88', '46', '87', '90', '113',
       '200', '210', '193', '?', '100', '105', '175', '153', '180', '110',
       '72', '86', '70', '76', '65', '69', '60', '80', '54', '208', '155',
       '112', '92', '145', '137', '158', '167', '94', '107', '230', '49',
       '75', '91', '122', '67', '83', '78', '52', '61', '93', '148',
       '129', '96', '71', '98', '115', '53', '81', '79', '120', '152',
       '102', '108', '68', '58', '149', '89', '63', '48', '66', '139',
       '103', '125', '133', '138', '135', '142', '77', '62', '132', '84',
       '64', '74', '116', '82'], dtype=object)

In [44]:
df['horsepower']=pd.to_numeric(df['horsepower'].replace('?',0.0))
print(df)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0
1    15.0          8         350.0       165.0    3693          11.5
2    18.0          8         318.0       150.0    3436          11.0
3    16.0          8         304.0       150.0    3433          12.0
4    17.0          8         302.0       140.0    3449          10.5
..    ...        ...           ...         ...     ...           ...
393  27.0          4         140.0        86.0    2790          15.6
394  44.0          4          97.0        52.0    2130          24.6
395  32.0          4         135.0        84.0    2295          11.6
396  28.0          4         120.0        79.0    2625          18.6
397  31.0          4         119.0        82.0    2720          19.4

     model year  origin                   car name
0            70       1  chevrolet chevelle malibu
1            70       1          buick skylark 320
2            70       1         plymouth satellite
3            70       1              amc rebel sst
4            70       1                ford torino
..          ...     ...                        ...
393          82       1            ford mustang gl
394          82       2                  vw pickup
395          82       1              dodge rampage
396          82       1                ford ranger
397          82       1                 chevy s-10

[398 rows x 9 columns]

In [41]:
df.corr()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
mpg,1.000000,-0.775396,-0.804203,-0.831741,0.420289,0.579267,0.563450
cylinders,-0.775396,1.000000,0.950721,0.896017,-0.505419,-0.348746,-0.562543
displacement,-0.804203,0.950721,1.000000,0.932824,-0.543684,-0.370164,-0.609409
weight,-0.831741,0.896017,0.932824,1.000000,-0.417457,-0.306564,-0.581024
acceleration,0.420289,-0.505419,-0.543684,-0.417457,1.000000,0.288137,0.205873
model year,0.579267,-0.348746,-0.370164,-0.306564,0.288137,1.000000,0.180662
origin,0.563450,-0.562543,-0.609409,-0.581024,0.205873,0.180662,1.000000

In [49]:
# q1 = read ipl-matches.csv
# q2 = find how many matches won in super over
# q3 = how many matches won by toss winner
# q4 = how many matches won by chennai super kings at kolkata

import pandas as pd
df=pd.read_csv('ipl-matches.csv')
print(df)

          ID        City        Date   Season  MatchNumber  \
0    1312200   Ahmedabad  2022-05-29     2022        Final
1    1312199   Ahmedabad  2022-05-27     2022  Qualifier 2
2    1312198     Kolkata  2022-05-25     2022   Eliminator
3    1312197     Kolkata  2022-05-24     2022  Qualifier 1
4    1304116      Mumbai  2022-05-22     2022           70
..       ...         ...         ...      ...          ...
945   335986     Kolkata  2008-04-20  2007/08            4
946   335985      Mumbai  2008-04-20  2007/08            5
947   335984       Delhi  2008-04-19  2007/08            3
948   335983  Chandigarh  2008-04-19  2007/08            2
949   335982   Bangalore  2008-04-18  2007/08            1

                           Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans
1    Royal Challengers Bangalore             Rajasthan Royals
2    Royal Challengers Bangalore         Lucknow Super Giants
3               Rajasthan Royals               Gujarat Titans
4            Sunrisers Hyderabad                 Punjab Kings
..                           ...                          ...
945        Kolkata Knight Riders              Deccan Chargers
946               Mumbai Indians  Royal Challengers Bangalore
947             Delhi Daredevils             Rajasthan Royals
948              Kings XI Punjab          Chennai Super Kings
949  Royal Challengers Bangalore        Kolkata Knight Riders

                                          Venue                   TossWinner  \
0              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals
1              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals
2                         Eden Gardens, Kolkata         Lucknow Super Giants
3                         Eden Gardens, Kolkata               Gujarat Titans
4                      Wankhede Stadium, Mumbai          Sunrisers Hyderabad
..                                          ...                          ...
945                                Eden Gardens              Deccan Chargers
946                            Wankhede Stadium               Mumbai Indians
947                            Feroz Shah Kotla             Rajasthan Royals
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
0            bat         N               Gujarat Titans  Wickets     7.0
1          field         N             Rajasthan Royals  Wickets     7.0
2          field         N  Royal Challengers Bangalore     Runs    14.0
3          field         N               Gujarat Titans  Wickets     7.0
4            bat         N                 Punjab Kings  Wickets     5.0
..           ...       ...                          ...      ...     ...
945          bat         N        Kolkata Knight Riders  Wickets     5.0
946          bat         N  Royal Challengers Bangalore  Wickets     5.0
947          bat         N             Delhi Daredevils  Wickets     9.0
948          bat         N          Chennai Super Kings     Runs    33.0
949        field         N        Kolkata Knight Riders     Runs   140.0

    method Player_of_Match                                       Team1Players  \
0      NaN       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
1      NaN      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
2      NaN      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
3      NaN       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
4      NaN   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...
..     ...             ...                                                ...
945    NaN       DJ Hussey  ['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...
946    NaN      MV Boucher  ['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...
947    NaN     MF Maharoof  ['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...
948    NaN      MEK Hussey  ['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...
949    NaN     BB McCullum  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...

                                          Team2Players        Umpire1  \
0    ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney
1    ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney
2    ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal
3    ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...   BNJ Oxenford
4    ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...   AK Chaudhary
..                                                 ...            ...
945  ['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...      BF Bowden
946  ['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...       SJ Davis
947  ['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...      Aleem Dar
948  ['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...      MR Benson
949  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...      Asad Rauf

            Umpire2
0       Nitin Menon
1       Nitin Menon
2          MA Gough
3         VK Sharma
4     NA Patwardhan
..              ...
945     K Hariharan
946       DJ Harper
947  GA Pratapkumar
948      SL Shastri
949     RE Koertzen

[950 rows x 20 columns]

In [50]:
df.loc[:,'SuperOver'].value_counts()

N    932
Y     14
Name: SuperOver, dtype: int64

In [51]:
df[(df['TossWinner']==['WinningTeam'].value_counts()

SyntaxError: unexpected EOF while parsing (<ipython-input-51-9c285685108e>, line 1)